# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               Aprenent Python
tagline:             'Fixant en memòria'
description:         'Construït amb <a href="http://jekyllrb.com" target="_blank">Jekyll</a>.<br />Disseny <a href="https://jekyllthemes.io/theme/15489219/lanyon">Laynon</a> per <a href="https://twitter.com/mdo" target="_blank">@mdo</a>'

url:                 'http://inclusa.github.io/python'
baseurl:             '/python'
paginate:            5

# About/contact
author:
  name:              Alfons Rovira
  url:               https://twitter.com/inclusa
  email:             inclusa@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]

# Server Port
port: 4001 # Canvia el port del servidor local al 4001
